name: React Native Android Build

on:
  push:
    branches:
      - main # or master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.run_number }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
